"""Conformance report rendering — JSON + markdown."""

from __future__ import annotations

import datetime as _dt
import io
import json
from dataclasses import asdict, dataclass, field
from typing import Optional


@dataclass
class ConformanceResult:
    case_name: str
    tier: str               # "core" | "full"
    severity: str           # "must" | "should"
    spec_ref: str
    passed: bool
    evidence: dict = field(default_factory=dict)
    error: Optional[str] = None
    elapsed_ms: float = 0.0


@dataclass
class ConformanceReport:
    results: list[ConformanceResult]
    adapter_repo: str
    server_label: str
    total_ms: float
    spec_version: str = "1.0.0"

    @property
    def core_passed(self) -> int:
        return sum(1 for r in self.results if r.tier == "core" and r.passed)

    @property
    def core_total(self) -> int:
        return sum(1 for r in self.results if r.tier == "core")

    @property
    def full_passed(self) -> int:
        return sum(1 for r in self.results if r.tier == "full" and r.passed)

    @property
    def full_total(self) -> int:
        return sum(1 for r in self.results if r.tier == "full")

    @property
    def core_compliant(self) -> bool:
        """All Core MUSTs pass — required for jMRI-Core compliance."""
        return self.core_total > 0 and self.core_passed == self.core_total

    @property
    def full_compliant(self) -> bool:
        """All Full SHOULDs pass *and* core passes — for jMRI-Full compliance."""
        if not self.core_compliant:
            return False
        return self.full_total > 0 and self.full_passed == self.full_total

    @property
    def verdict(self) -> str:
        if self.full_compliant:
            return "jMRI-Full compliant"
        if self.core_compliant:
            if self.full_total == 0:
                return "jMRI-Core compliant (Full not assessed)"
            shortfall = self.full_total - self.full_passed
            return f"jMRI-Core compliant; Full has {shortfall} SHOULD shortfall(s)"
        shortfall = self.core_total - self.core_passed
        return f"NOT compliant — {shortfall} Core MUST failure(s)"

    def to_json(self, indent: int = 2) -> str:
        payload = {
            "spec_version": self.spec_version,
            "server_label": self.server_label,
            "adapter_repo": self.adapter_repo,
            "generated_at": _dt.datetime.now(_dt.timezone.utc).isoformat(),
            "verdict": self.verdict,
            "core": {
                "passed": self.core_passed, "total": self.core_total,
                "compliant": self.core_compliant,
            },
            "full": {
                "passed": self.full_passed, "total": self.full_total,
                "compliant": self.full_compliant,
            },
            "total_ms": self.total_ms,
            "results": [asdict(r) for r in self.results],
        }
        return json.dumps(payload, indent=indent)

    def to_markdown(self) -> str:
        out = io.StringIO()
        out.write(f"# jMRI Conformance Report — {self.server_label}\n\n")
        out.write(f"**Spec version:** {self.spec_version}  \n")
        out.write(f"**Repo under test:** `{self.adapter_repo}`  \n")
        out.write(f"**Verdict:** {self.verdict}  \n")
        out.write(f"**Wall clock:** {self.total_ms:.1f} ms\n\n")

        emoji = "✅" if self.core_compliant else "❌"
        out.write(f"## Core (MUST) — {emoji} {self.core_passed}/{self.core_total}\n\n")
        out.write("| Case | Result | Spec |\n|---|---|---|\n")
        for r in self.results:
            if r.tier != "core":
                continue
            mark = "✅" if r.passed else "❌"
            note = "" if r.passed else f" — {r.error or ''}"
            out.write(f"| `{r.case_name}` | {mark}{note} | {r.spec_ref} |\n")
        out.write("\n")

        if self.full_total > 0:
            emoji = "✅" if self.full_compliant else "⚠️"
            out.write(f"## Full (SHOULD) — {emoji} {self.full_passed}/{self.full_total}\n\n")
            out.write("| Case | Result | Spec |\n|---|---|---|\n")
            for r in self.results:
                if r.tier != "full":
                    continue
                mark = "✅" if r.passed else "⚠️"
                note = "" if r.passed else f" — {r.error or ''}"
                out.write(f"| `{r.case_name}` | {mark}{note} | {r.spec_ref} |\n")
            out.write("\n")

        out.write(
            "_Generated by `jmri.conformance` v1.0. "
            "Run `python -m jmri.conformance --help` for re-run options._\n"
        )
        return out.getvalue()
